### PR TITLE
Update Profiles- New Contributors

### PR DESCRIPTION
**Pull request by adit2005**

### CODE REVIEW

**Comment by adit2005** [comment]
HI AKANSHA MYSELF ADITYA FROM DELHI. I AM ALSO AN AI-ML ENTHUSIAST . WOULD LIKE TO CONTRIBUTE MORE ON PROJECTS RELATED TO ML. PLEASE ACCEPT MY PULL REQUEST.

**Comment by adit2005** [comment]
I HAVE ADDED A PROJECT OF CAR PRICE PREDICTION.

**Comment by adit2005** [comment]
ALSO I HAVE UPLOADED MY PHOTO AND DETAILS.

**Comment by adit2005** [comment]
I have deleted my file which i added by mistake. Now my pull request has only image and details. please merge it.

**Comment by AkankshaAI** [comment]
image


Hey, @adit2005 Seems like you have made edits with updating to repo to latest commits. So requesting if you can update and that commit changes, and then make the PR.
Regards,
Akanksha

**Pull request closed without merging**
